version: '3.8'

services:
  kin-gallery:
    build: .
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/kin-gallery.db
      - MEDIA_PATH=/app/media
    volumes:
      - ./data:/app/data
      - ./media:/app/media
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4321/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
  media: